# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
          os: [ubuntu-latest, macos-10.15]
          container-runtime: ['', 'containerd']
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Tools for MacOs
        if: matrix.os == 'macos-10.15'
        run: |
          brew install docker-machine docker
          sudo docker --version
          VBoxManage --version
          sysctl hw.physicalcpu hw.logicalcpu 
        continue-on-error: true
      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        with:
          container-runtime: ${{ matrix.container-runtime }}
      - name: Start minikube Again for fun
        uses: medyagh/setup-minikube@latest
        with:
          container-runtime: ${{ matrix.container-runtime }}
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Use Docker-Env Feature
        if: matrix.container-runtime == ''
        run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker images
      - name: Use Podman-Env Feature
        if: matrix.container-runtime == 'crio'
        run: | 
          export SHELL=/bin/bash
          eval $(minikube -p minikube podman-env)
          minikube ssh podman images
      - name: Create Namespace
        run: kubectl create namespace ns-bluegreendeployment
      - name: Deploy Blue Deployment
        run: kubectl apply -f ./kubernetes/blue-deploy.yaml -n ns-bluegreendeployment
      - name: Display Blue Deployment details
        run: kubectl get deployment -n ns-bluegreendeployment
      - name: Green Deployment
        run: kubectl apply -f ./kubernetes/green-deploy.yaml -n ns-bluegreendeployment
      - name: Deploy the Service yaml
        run: kubectl apply -f ./kubernetes/service.yaml -n ns-bluegreendeployment
      - name: List all ns-bluegreendeployment deployments
        run: kubectl get all ns-bluegreendeployment
        
